language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4
install:
  - pip install argparse --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script:
  - python uwc_first_stage/quicktest.py core products providers
