language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO_VERSION=1.4
install:
 - pip install -r requirements.txt --use-mirrors
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
script:  nosetests
